---
layout: single
title: "Hi, I’m Lucy 👋"
classes: wide
logo: "/assets/img/logo.png"

---

<p class="lead">{{ site.description }}</p>

<div class="btns">
  <a class="btn btn--primary" href="/assets/docs/LucyInett-CV.pdf" target="_blank">Download CV</a>
  <a class="btn" href="/projects/">Projects</a>
  <a class="btn" href="/articles/">Articles</a>
</div>

### Featured Projects
- **Spotify Dashboard** — Streamlit app visualising my listening patterns. [GitHub »](https://github.com/...)
- **Recommender System (Dissertation)** — React + Java + Python microservice. [GitHub »](https://github.com/...)
