title: "Lucy Inett"
description: "MSc CS | Software & Data"
url: "https://lucyinett.co.uk"
baseurl: ""

remote_theme: "mmistakes/minimal-mistakes@4.24.0"
minimal_mistakes_skin: "mint"
logo: /assets/img/logo.png
breadcrumbs: false
locale: en-GB

plugins:
  - jekyll-remote-theme
  - jekyll-seo-tag
  - jekyll-feed
  - jekyll-include-cache


<p class="lead">{{ site.description }}</p>

<div class="btns">
  <a class="btn btn--primary" href="/assets/docs/LucyInett-CV.pdf" target="_blank">Download CV</a>
  <a class="btn" href="/projects/">Projects</a>
  <a class="btn" href="/articles/">Articles</a>
</div>

### Featured Projects
- **Spotify Dashboard** — Streamlit app visualising my listening patterns. [GitHub »](https://github.com/...)
- **Recommender System (Dissertation)** — React + Java + Python microservice. [GitHub »](https://github.com/...)
