title: "Lucy Inett"
description: "MSc Computer Science | Software & Data Enthusiast"
url: "https://lucyinett.co.uk"   # your custom domain
baseurl: ""                      # leave blank for root domain

# Use Minimal Mistakes remote theme
remote_theme: "mmistakes/minimal-mistakes@4.24.0"
  # you can switch to "default", "air", "dark", etc.

# Logo in navbar
logo: "/assets/img/logo.png"

# Optional site settings
breadcrumbs: false
locale: en-GB

# Social links (show in header/footer if enabled)
author:
  name: "Lucy Inett"
  avatar: "/assets/img/avatar.png"   # optional profile photo
  bio: "MSc CS student | Interested in data, AI, and software engineering"
  location: "UK"
  links:
    - label: "Email"
      icon: "fas fa-envelope"
      url: "mailto:lucyinett@protonmail.com"
    - label: "GitHub"
      icon: "fab fa-github"
      url: "https://github.com/lucyinett"
    - label: "LinkedIn"
      icon: "fab fa-linkedin"
      url: "https://linkedin.com/in/lucyinett"

# Plugins GitHub Pages supports
plugins:
  - jekyll-remote-theme
  - jekyll-seo-tag
  - jekyll-feed
  - jekyll-include-cache

# Build settings
markdown: kramdown
permalink: /:categories/:title/
paginate: 5
paginate_path: "/page:num/"

collections:
  pages:
    output: true
    permalink: /:name/

# Defaults so pages render nicely
defaults:
  - scope:
      path: ""
      type: pages
    values:
      layout: single
      classes: wide